default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 8 } %>
  host: 172.104.142.218
  username: <%= ENV.fetch("DB_LOGIN_USER") %>
  password: <%= ENV.fetch("DB_LOGIN_PASW") %>
  timeout: 5000
  variables:
    statement_timeout: <%= ENV["DB_STATEMENT_TIMEOUT"] || 120_000 %>

development:
  <<: *default
  database: code_challenge_rails_development

test:
  <<: *default
  database: code_challenge_rails_test

staging:
  <<: *default
  url: <%= Rails.application.credentials.database_url %>

production:
  <<: *default
  url: <%= Rails.application.credentials.database_url %>
