Airport.create(name: "Utirik Airport",iata: "UTK", icao: "K03N", country_alpha2: "MH", country: "MH/Utirik Island")
Airport.create(name: "Ocean Reef Club Airport",iata: "OCA", icao: "07FA", country_alpha2: "US", country: "US/Key Largo")
Airport.create(name: "Pilot Station Airport", iata: "PQS", icao: nil, country_alpha2: "US", country: "US/Pilot Station")
Airport.create(name: "Crested Butte Airpark",iata: "CSE", icao: "0CO2", country_alpha2: "US", country: "US/Crested Butte")
Airport.create(name: "LBJ Ranch Airport",iata: "JCY", icao: "0TE7", country_alpha2: "US", country: "US/Johnson City")
Airport.create(name: "Metropolitan Airport",iata: "PMX", icao: nil, country_alpha2: "US", country: "US/Palmer")
Airport.create(name: "Loring Seaplane Base",iata: "WLR", icao: "13Z", country_alpha2: "US", country: "US/Loring")
Airport.create(name: "Nunapitchuk Airport",iata: "NUP", icao: "PPIT", country_alpha2: "US", country: "US/Nunapitchuk")
Airport.create(name: "Port Alice Seaplane Base",iata: "PTC", icao: "16K", country_alpha2: "US", country: "US/Port Alice")
Airport.create(name: "Icy Bay Airport",iata: "ICY", icao: "19AK", country_alpha2: "US", country: "US/Icy Bay")
Airport.create(name: "Port Protection Seaplane Base",iata: "PPV", icao: "19P", country_alpha2: "US", country: "US/Port Protection")
Airport.create(name: 'Adado Airport',iata: 'AAD', icao: nil, country_alpha2: 'SO', country: 'SO/Adado', passenger_volume: 100)
Airport.create(name: 'Atkamba Airport',iata: 'ABP', icao: nil, country_alpha2: 'PG', country: 'PG/Atkamba Mission', passenger_volume: 90)
Airport.create(name: 'Abau Airport',iata: 'ABW', icao: nil, country_alpha2: 'PG', country: 'PG/Abau', passenger_volume: 80)
Airport.create(name: 'Woodland Airpark (duplicate)',iata: 'WAP', icao: nil, country_alpha2: 'PH', country: 'PH/Magalang', passenger_volume: 100)
Airport.create(name: 'Andorra la Vella (Our Lady of Meritxell Hospital) Heliport',iata: 'ALV', icao: nil, country_alpha2: 'AD', country: 'AD/Escaldes-Engordany', passenger_volume: 90)
Airport.create(name: 'Andakombe Airport',iata: 'ADC', icao: 'AYAN', country_alpha2: 'PG', country: 'PG/Andekombe', passenger_volume: 40)
Airport.create(name: 'El Daein Airport',iata: 'ADV', icao: nil, country_alpha2: 'SD', country: 'SD/El Daein', passenger_volume: 50)
Airport.create(name: 'Jebel Ali Seaplane Base',iata: 'DJH', icao: nil, country_alpha2: 'AE', country: 'AE/Jebel Ali', passenger_volume: 100)
Airport.create(name: 'Adareil Airport',iata: 'AEE', icao: nil, country_alpha2: 'SS', country: 'SS/', passenger_volume: 10)
Airport.create(name: 'Algeciras Heliport',iata: 'AEI', icao: 'LEAG', country_alpha2: 'ES', country: 'ES/Algeciras', passenger_volume: 40)
